train: '../data/train' # Input train data for preprocessing and modelling

test: '../data/test' # Input test data for preprocessing and modelling

modelling:
  model_name: 'ResNet50'
  epochs: 50

evaluation:
  plot: 'evaluation/plots'
  plot_to_file: True

test_videos:
  - 5
  - 11
  - 14
  - 22
  - 32
  - 42
  - 53
  - 63
  - 73
  - 81
  - 90
  - 100
  - 110
  - 120
  - 130
  - 140
  - 150
  - 160
  - 170
  - 180
  - 190
  - 200
  - 210
  - 220
  - 230
  - 240
  - 250
  - 260
  - 270
  - 280
  - 290
  - 299
  - 307
  - 314
  - 324